# Generated by Django 5.0.7 on 2024-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_foodlog_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='weight_trained',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='name_of_exercise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
