# Generated by Django 5.0.7 on 2024-11-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_workoutplan_reps_workoutplan_sets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
