# Generated by Django 5.0.7 on 2024-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_workoutplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
