# Generated by Django 5.0.7 on 2024-11-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_workoutplan_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='type',
            field=models.CharField(blank=True, choices=[('arms', 'Arms'), ('back', 'Back'), ('chest', 'Chest'), ('legs', 'Legs'), ('shoulders', 'Shoulders')], max_length=50, null=True),
        ),
    ]
