# Generated by Django 5.0.7 on 2024-11-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_workoutplan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='is_default',
        ),
    ]
